client_config_backend: settings
client_config:
  client_id: 203948572398475-yourclientid.apps.googleusercontent.com
  client_secret: YOURCLIENTSECRET

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive